# Generated by Django 4.2.1 on 2023-06-20 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo (pago en local)'), ('debito', 'Tarjeta de débito'), ('credito', 'Tarjeta de crédito')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
